replicaCount: 1

image:
  repository: invoiceninja/invoiceninja
  tag: 4.5.4

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  hosts:
    - invoiceninja.local

persistence:
  accessMode: ReadWriteOnce
  size: 2Gi
  existingClaim: ""
  storageClassName: ""

global:
  persistence:
    enabled: false
