---
apiVersion: gitkube.sh/v1alpha1
kind: Remote
metadata:
  name: {{ .Release.Name }}
  namespace: default
spec:
  deployments:
    - name: {{ .Release.Name }}-custom
      containers:
        - name: {{ .Release.Name }}-custom
          path: .
          dockerfile: Dockerfile
  authorizedKeys:
    - ssh-rsa {{ .Values.sshKey }}
