apiVersion: v1
kind: Service
metadata:
  name: {{ template "custom.fullname" . }}
  labels:
    app: {{ template "custom.name" . }}
    chart: {{ template "custom.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    email: {{ .Values.email }}
    category: {{ index .Chart.Keywords 0 }}
    {{ if .Values.ingress.hosts }}
    domain: {{ index .Values.ingress.hosts 0 }}
    {{ end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "custom.name" . }}
    release: {{ .Release.Name }}
