apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "etherpad.fullname" . }}
  labels:
    app: {{ template "etherpad.name" . }}
    chart: {{ template "etherpad.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "etherpad.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "etherpad.name" . }}
        release: {{ .Release.Name }}
      annotations:
        backup.ark.heptio.com/backup-volumes: etherpad-data
    spec:
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: etherpad-data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "etherpad.fullname" .) }}
      {{ end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: etherpad-data
              mountPath: /opt/etherpad-lite/var
              subPath: var
          {{ end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
