apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "mariadb.fullname" . }}
  labels:
    app: {{ template "mariadb.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "mariadb.name" . }}
        release: {{ .Release.Name }}
    spec:
      {{ if .Values.persistence.enabled }}
      volumes:
        {{ if .Values.persistence.existingClaim }}
        - name: mariadb-storage
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
        {{ else }}
        - name: mariadb-storage
          hostPath:
            path: {{ .Values.persistence.directory }}/{{ .Release.Name }}/{{ template "mariadb.fullname" . }}
            type: DirectoryOrCreate
        {{ end }}
      {{ end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MYSQL_DATABASE
              value: ninja
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "mariadb.fullname" . }}
                  key: mariadb-root-password
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: mariadb-storage
              mountPath: "/var/lib/mysql"
          {{ end }}
          livenessProbe:
            exec:
              command: ["sh", "-c", "exec mysqladmin status -uroot -p$MYSQL_ROOT_PASSWORD"]
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command: ["sh", "-c", "exec mysqladmin status -uroot -p$MYSQL_ROOT_PASSWORD"]
            initialDelaySeconds: 5
            timeoutSeconds: 1
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
