replicaCount: 1

image:
  repository: mariadb
  tag: 10.3.9

service:
  type: ClusterIP
  port: 3306

persistence:
  enabled: false
  accessMode: ReadWriteOnce
  size: 2Gi
  existingClaim: ""
  storageClassName: ""
