apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "ethibox.fullname" . }}
  labels:
    app: {{ template "ethibox.name" . }}
    chart: {{ template "ethibox.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "ethibox.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "ethibox.name" . }}
        release: {{ .Release.Name }}
    spec:
      hostNetwork: true
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: ethibox-storage
          persistentVolumeClaim:
            claimName: ethibox-pv-claim
      {{ end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SECRET
              value: {{ randAlphaNum 10 | b64enc | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - mountPath: "/root/.ethibox"
              name: ethibox-storage
          {{ end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
