{{- if .Values.persistence.enabled }}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: ethibox-pv-volume
  labels:
    type: local
spec:
  storageClassName: ethibox
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/ethibox/"
{{ end }}
