replicaCount: 1

image:
  repository: fuerst/etherpad-docker
  tag: stable

service:
  type: NodePort
  port: 9001

ingress:
  enabled: false
  hosts:
    - etherpad.local

persistence:
  enabled: false
  accessMode: ReadWriteOnce
  size: 2Gi
  # existingClaim: your-claim
  # storageClassName: "-"
