{{- if .Values.persistence.enabled }}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ template "invoiceninja.fullname" . }}
  labels:
    type: local
spec:
  storageClassName: invoiceninja
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /opt/{{ template "invoiceninja.fullname" . }}
{{ end }}
