replicaCount: 1

image:
  repository: ethibox/ethibox
  tag: 0.11.0

service:
  type: ClusterIP
  port: 4444

ingress:
  enabled: false
  hosts:
    - ethibox.local

persistence:
  enabled: false
  accessMode: ReadWriteOnce
  size: 2Gi
  existingClaim: ""
  storageClassName: ""
