replicaCount: 1

image:
  repository: ston3o/ethibox
  tag: 0.9.1

service:
  type: NodePort
  port: 4444

ingress:
  enabled: false
  hosts:
    - ethibox.local

persistence:
  enabled: false
  accessMode: ReadWriteOnce
  size: 2Gi
  existingClaim: ""
  storageClassName: ""
